apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-itsf
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # It's fine for this test but ReadWriteMany for real prod workload or even ReadOnlyMany for read-only data
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
